window.BOOK_SECTIONS = [
  { title: "序", time: 12.7, chapter: true },
  { title: "默想", time: 85.1, chapter: false },
  { title: "第1章 《圣经》对工作的教导——体现人的意义与价值", time: 355.1, chapter: true },
  { title: "什么是工作", time: 401.9, chapter: false },
  { title: "工作的起源", time: 1503.9, chapter: false },
  { title: "默想", time: 2136.4, chapter: false },
  { title: "第2章 工作是神给的祝福——喜乐与满足的赏赐", time: 2158.4, chapter: true },
  { title: "罪的后果", time: 2245.5, chapter: false },
  { title: "虚空的虚空", time: 2619.5, chapter: false },
  { title: "神救赎的应许", time: 3062.3, chapter: false },
  { title: "神美好的计划", time: 3717.2, chapter: false },
  { title: "工作的目的与价值", time: 3942.0, chapter: false },
  { title: "默想", time: 4535.9, chapter: false },
  { title: "第3章 工作中的永恒价值——模塑成主的样式", time: 4562.9, chapter: true },
  { title: "永恒的价值", time: 4677.1, chapter: false },
  { title: "谁能决定永恒的价值", time: 5066.2, chapter: false },
  { title: "生命的展现才是永恒", time: 5466.5, chapter: false },
  { title: "主权在神，听凭呼召", time: 5853.9, chapter: false },
  { title: "默想", time: 6745.5, chapter: false },
  { title: "第4章 寻求合神心意的工作——万事皆服侍", time: 6762.1, chapter: true },
  { title: "工作即侍奉，工人即祭司", time: 6839.6, chapter: false },
  { title: "为神而做", time: 7417.9, chapter: false },
  { title: "讨神喜悦的服侍", time: 7989.4, chapter: false },
  { title: "遵循主的教诲", time: 8563.7, chapter: false },
  { title: "默想", time: 8953.8, chapter: false },
  { title: "第5章 工作中的金钱观——谋求人类的最大福祉", time: 8978.8, chapter: true },
  { title: "金钱可以决定一切吗", time: 9105.0, chapter: false },
  { title: "胜过金钱的诱惑", time: 9459.3, chapter: false },
  { title: "工作中当得的利益", time: 9885.2, chapter: false },
  { title: "谋求人类的最大福祉", time: 10406.6, chapter: false },
  { title: "默想", time: 10885.4, chapter: false },
  { title: "第6章 财富之于工作——做神忠心的好管家", time: 10920.3, chapter: true },
  { title: "钱财是神给的托付", time: 11019.9, chapter: false },
  { title: "做神忠心的好管家", time: 11442.1, chapter: false },
  { title: "君子爱财取之有道", time: 12140.9, chapter: false },
  { title: "神是我们一切的供应", time: 12508.4, chapter: false },
  { title: "默想", time: 12800.0, chapter: false },
  { title: "第7章 按神的心意工作——听命的必能蒙福", time: 12824.8, chapter: true },
  { title: "听命胜于努力", time: 12941.7, chapter: false },
  { title: "盼望不在今世", time: 13497.0, chapter: false },
  { title: "做钱财的主人", time: 14100.3, chapter: false },
  { title: "受与施", time: 14503.2, chapter: false },
  { title: "默想", time: 14880.6, chapter: false },
  { title: "第8章 做工的得工价——按所行的得赏赐", time: 14918.4, chapter: true },
  { title: "得胜荣耀主", time: 15074.3, chapter: false },
  { title: "做工的得工价", time: 15474.2, chapter: false },
  { title: "不可亏负人", time: 16053.1, chapter: false },
  { title: "敬虔知足的必然蒙福", time: 16489.3, chapter: false },
  { title: "默想", time: 16820.6, chapter: false },
  { title: "第9章 通过工作建造品格——以生命服侍，荣耀益人", time: 16851.4, chapter: true },
  { title: "工作的终极目的", time: 17082.2, chapter: false },
  { title: "工作是塑造品格的机会", time: 17536.9, chapter: false },
  { title: "好品格的建立要靠神的大能", time: 18079.7, chapter: false },
  { title: "定睛于永恒的赏赐", time: 18554.7, chapter: false },
  { title: "默想", time: 19146.4, chapter: false },
  { title: "第10章 工作与你的关系——成为工作的真主人", time: 19178.8, chapter: true },
  { title: "尽心竭力地服侍", time: 19293.1, chapter: false },
  { title: "神的恩典大过一切", time: 19706.2, chapter: false },
  { title: "通过工作模塑品格", time: 20093.5, chapter: false },
  { title: "仆人领袖", time: 20544.8, chapter: false },
  { title: "活出神的荣美", time: 20775.5, chapter: false },
];
